apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector-collector
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.collector.serviceAccount.roleArn }}
