<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="Services\**" />
    <Content Remove="bin\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="bin\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Bedrock" Version="4.0.9" />
    <PackageReference Include="AWSSDK.BedrockAgent" Version="4.0.4.2" />
    <PackageReference Include="AWSSDK.BedrockAgentRuntime" Version="4.0.4.11" />
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="4.0.3" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.26.1" />
    <PackageReference Include="AWSSDK.OpenSearchServerless" Version="4.0.1.1" />
    <PackageReference Include="AWSSDK.OpenSearchService" Version="4.0.2.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.6.3" />
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Markdown.ColorCode" Version="3.0.0" />
    <PackageReference Include="MudBlazor" Version="6.21.0" />
    <PackageReference Include="OpenSearch.Client" Version="1.8.0" />
    <PackageReference Include="OpenSearch.Net.Auth.AwsSigV4" Version="1.8.0" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="System.Memory.Data" Version="9.0.8" />
  </ItemGroup>

</Project>
