namespace: hello-world-api
replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/hello-world-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

grpcService:
  url: "http://grpc-hello-service.grpc-hello-service.svc.cluster.local:8080"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

instrumentation:
  serviceName: hello-world-api
  otlpEndpoint: "http://adot-collector-collector:4317"
  dotnetImage: "public.ecr.aws/aws-observability/adot-autoinstrumentation-dotnet:v1.11.1"

collector:
  mode: deployment
  replicas: 2
  healthCheckPort: 13133
  otlpPort: 4317
  serviceAccount:
    name: adot-collector-collector
    roleArn: "arn:aws:iam::{ACCOUNT_ID}:role/eksctl-my-cluster-addon-iamserviceaccount-hel-Role1-bm1Dxo5TZJ3S"
  cloudwatch:
    region: us-west-2
    namespace: HelloWorldApi
  xray:
    region: us-west-2
